# Generated by Django 5.1.1 on 2024-09-26 04:54

import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(default=employees.models.generate_id, editable=False, max_length=21, primary_key=True, serialize=False, verbose_name='id')),
                ('full_name', models.CharField(max_length=100, verbose_name='full name')),
                ('phone_number', models.CharField(max_length=22)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('avatar', models.ImageField(blank=True, upload_to='ar/realtors/')),
                ('is_mvp', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('role', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
