# Generated by Django 5.1.1 on 2024-09-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='id',
            field=models.CharField(default='VjC0hteUapn9eH3Ya1W17', editable=False, max_length=21, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
