# Generated by Django 5.1.1 on 2024-09-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0008_alter_identity_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identity',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='identity',
            name='id',
            field=models.CharField(default='IhPfsymr_QaUffyjxP9Gy', editable=False, max_length=21, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
